export interface TourItem {
  id: string;
  category: "dashboards" | "attendance" | "academics" | "admin";
  categoryLabel: string;
  title: string;
  roleBadge: string;
  badgeColor: string;
  description: string;
  features: string[];
  webImage: string;
  mobileImage: string;
  webUrl: string;
  extraWebImage?: string;
  extraLabel?: string;
}

export const TOUR_ITEMS: TourItem[] = [
  {
    id: "admin-dashboard",
    category: "dashboards",
    categoryLabel: "Executive & Admin",
    title: "Administrator Command Center",
    roleBadge: "Admin Role",
    badgeColor: "bg-indigo-100 text-indigo-700 border-indigo-200",
    description: "Centralized school governance providing real-time headcount, daily check-in metrics, class rankings, and administrative control.",
    features: [
      "Total students and active faculty metrics",
      "Real-time teacher and student daily attendance ratio",
      "Top rankers leaderboard by class",
      "Quick access to classes, announcements, and settings",
    ],
    webImage: "/Tour/Web_Admin_Dashboard.png",
    mobileImage: "/Tour/Mobile_Admin_Dashboard.png",
    webUrl: "myschool.app/admin",
  },
  {
    id: "principal-dashboard",
    category: "dashboards",
    categoryLabel: "Executive & Admin",
    title: "Principal Academic Overview",
    roleBadge: "Principal Role",
    badgeColor: "bg-purple-100 text-purple-700 border-purple-200",
    description: "Institution-wide academic monitoring with faculty attendance status, classroom performance, and swift administrative reporting.",
    features: [
      "Campus-wide student & teacher enrollment counts",
      "Faculty check-in tracking & attendance summary",
      "Class-by-class academic rankers & pass rates",
      "Direct shortcuts to notices, classes, and exams",
    ],
    webImage: "/Tour/Web_Principal_Dashboard.png",
    mobileImage: "/Tour/Mobile_Principal_Dashboard.png",
    webUrl: "myschool.app/principal",
  },
  {
    id: "teacher-dashboard",
    category: "dashboards",
    categoryLabel: "Teacher & Academics",
    title: "Teacher Daily Portal",
    roleBadge: "Teacher Role",
    badgeColor: "bg-blue-100 text-blue-700 border-blue-200",
    description: "Personalized workspace for faculty to record class attendance, manage homework assignments, enter exam marks, and monitor students.",
    features: [
      "Assigned classroom overview & student count",
      "One-click 'Take Attendance' action",
      "Homework creation with due dates & attachments",
      "Direct entry for exams and subject marks",
    ],
    webImage: "/Tour/Web_Teacher_Dashboard.png",
    mobileImage: "/Tour/Mobile_Teacher_Dashboard.png",
    webUrl: "myschool.app/teacher",
  },
  {
    id: "student-dashboard",
    category: "dashboards",
    categoryLabel: "Student & Parent",
    title: "Student Learning Dashboard",
    roleBadge: "Student Role",
    badgeColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    description: "Student portal showcasing personal attendance rates, assigned homework tasks, exam report cards, and school-wide announcements.",
    features: [
      "Personal attendance percentage & present days",
      "Upcoming & pending homework assignments",
      "Official exam progress cards with downloadable PDF",
      "Instant school alerts and campus notices",
    ],
    webImage: "/Tour/Web_Student_Dashboard.png",
    mobileImage: "/Tour/Mobile_Student_Dashboard.png",
    webUrl: "myschool.app/student",
  },
  {
    id: "parent-dashboard",
    category: "dashboards",
    categoryLabel: "Student & Parent",
    title: "Parent Multi-Child Portal",
    roleBadge: "Parent Role",
    badgeColor: "bg-amber-100 text-amber-700 border-amber-200",
    description: "Unified parent interface with seamless child switching, real-time daily attendance updates, homework status, and exam scorecards.",
    features: [
      "Multi-child selector with instant profile switching",
      "Live daily attendance status (Present / Absent / Late)",
      "Homework tasks with file downloads & teacher notes",
      "Official term progress card view and download",
    ],
    webImage: "/Tour/Web_Parent_Dashboard.png",
    mobileImage: "/Tour/Mobile_Parents_Dashboard.png",
    webUrl: "myschool.app/parent",
  },
  {
    id: "attendance-marking",
    category: "attendance",
    categoryLabel: "Attendance & Reports",
    title: "Daily Attendance Marking",
    roleBadge: "Daily Operations",
    badgeColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    description: "Fast, error-free attendance register allowing teachers and admins to mark present, absent, or late with one-click bulk presets.",
    features: [
      "Date selector with instant class and section loading",
      "Present, Absent, and Late status toggles per student",
      "'Mark All Present' batch action for maximum speed",
      "Instant synchronization across web and mobile platforms",
    ],
    webImage: "/Tour/Web_Attendance_Marking.png",
    mobileImage: "/Tour/Mobile_Attendance_Marking.png",
    webUrl: "myschool.app/teacher/attendance",
  },
  {
    id: "attendance-reports",
    category: "attendance",
    categoryLabel: "Attendance & Reports",
    title: "Attendance Analytics & History",
    roleBadge: "Analytics",
    badgeColor: "bg-indigo-100 text-indigo-700 border-indigo-200",
    description: "In-depth attendance breakdown across classes and date ranges with present vs absent statistics and historical records.",
    features: [
      "Class-wise attendance percentage and total present counts",
      "Historical date filter for daily and monthly reviews",
      "Identification of students requiring attendance intervention",
      "Real-time chart visualization of campus attendance trends",
    ],
    webImage: "/Tour/Web_Admin_Attendance_Reports.png",
    mobileImage: "/Tour/Mobile_Admin_Attendance_Reports.png",
    webUrl: "myschool.app/admin/attendance",
  },
  {
    id: "parent-attendance-monitor",
    category: "attendance",
    categoryLabel: "Attendance & Reports",
    title: "Parent Attendance Calendar",
    roleBadge: "Parent Monitoring",
    badgeColor: "bg-teal-100 text-teal-700 border-teal-200",
    description: "Monthly calendar grid and chronological timeline giving parents complete transparency into their child's attendance record.",
    features: [
      "Visual monthly calendar with color-coded status badges",
      "Total present days, absent count, and percentage summary",
      "Day-by-day attendance history and arrival timestamps",
      "Automated alerts on recorded absences",
    ],
    webImage: "/Tour/Web_Parent_Attendance_Moniter.png",
    mobileImage: "/Tour/Mobile_Parent_Attendance_Moniter.png",
    webUrl: "myschool.app/parent/attendance",
  },
  {
    id: "leave-notification",
    category: "attendance",
    categoryLabel: "Attendance & Reports",
    title: "Parent Leave & Absence Monitoring",
    roleBadge: "Real-Time Alerts",
    badgeColor: "bg-rose-100 text-rose-700 border-rose-200",
    description: "Instant push notifications and real-time alerts sent directly to parents when a teacher marks a student absent or records leave.",
    features: [
      "Instant push notifications delivered to parents on attendance submission",
      "Notification specifies student name, class, section, and date",
      "Daily and monthly attendance calendar review",
      "Direct oversight on both Mobile App and Web Portal",
    ],
    webImage: "/Tour/Web_Parent_Attendance_Moniter.png",
    mobileImage: "/Tour/Mobile_Leave_Notification.png",
    webUrl: "myschool.app/parent/attendance",
  },
  {
    id: "exams-and-marks",
    category: "academics",
    categoryLabel: "Exams & Academics",
    title: "Exams, Grading & Progress Cards",
    roleBadge: "Academic Grading",
    badgeColor: "bg-rose-100 text-rose-700 border-rose-200",
    description: "End-to-end examination management with flexible mark splits, digital grade entry, automated calculations, and official Progress Card downloads.",
    features: [
      "Exam setup with customizable split criteria (Theory, Practical, Oral)",
      "Subject-wise marks entry with max and pass thresholds",
      "Automatic total, percentage, grade, and pass/fail calculation",
      "Official Progress Card export as high-resolution Image and PDF",
    ],
    webImage: "/Tour/Web_Exams_and_Marks.png",
    mobileImage: "/Tour/Mobile_Exams_and _Marks.png",
    webUrl: "myschool.app/teacher/exams",
  },
  {
    id: "progress-card",
    category: "academics",
    categoryLabel: "Exams & Academics",
    title: "Auto-Generated Progress Card",
    roleBadge: "Student & Parent",
    badgeColor: "bg-emerald-100 text-emerald-700 border-emerald-200",
    description: "Automated progress card generation with detailed subject splits, total marks, percentage, grade, and one-click download as high-resolution Image or PDF for students and parents.",
    features: [
      "Auto-calculated subject splits (Theory, Practical, Oral)",
      "Automated total marks, overall percentage, and grade",
      "Available instantly for both Students and Parents to view",
      "One-click high-resolution PNG image and PDF report card download",
    ],
    webImage: "/Tour/Progress_Card.png",
    mobileImage: "/Tour/Mobile_Exams_and _Marks.png",
    webUrl: "myschool.app/student/marks",
  },
  {
    id: "homework-management",
    category: "academics",
    categoryLabel: "Exams & Academics",
    title: "Homework & Multi-Attachment Sharing",
    roleBadge: "Assignments",
    badgeColor: "bg-amber-100 text-amber-700 border-amber-200",
    description: "Digital assignment distribution enabling teachers to attach reference materials and students/parents to access coursework anywhere.",
    features: [
      "Assignment creation with class, section, and subject targeting",
      "Due date scheduling with urgency badges",
      "Multi-file attachments (images, PDFs, documents) stored in database",
      "In-app image preview lightbox and direct file download",
    ],
    webImage: "/Tour/Web_HW_Page.png",
    mobileImage: "/Tour/Mobile_Hw_Page.png",
    webUrl: "myschool.app/teacher/homework",
  },
  {
    id: "campus-notices",
    category: "admin",
    categoryLabel: "Communication & Admin",
    title: "Campus Notices & Announcements",
    roleBadge: "Broadcasts",
    badgeColor: "bg-sky-100 text-sky-700 border-sky-200",
    description: "School-wide and targeted communication system for broadcasting urgent notices, event schedules, and administrative circulars.",
    features: [
      "Role-based targeting (All, Teachers, Students, Parents)",
      "Priority badges and publication dates",
      "Notice author details and institutional stamp",
      "Instant delivery indicators across web and mobile apps",
    ],
    webImage: "/Tour/Web_Notices_Page.png",
    mobileImage: "/Tour/Mobile_Notices_Page.png",
    webUrl: "myschool.app/admin/announcements",
  },
  {
    id: "bulk-student-upload",
    category: "admin",
    categoryLabel: "Communication & Admin",
    title: "Bulk Student Excel/CSV Upload",
    roleBadge: "Quick Onboarding",
    badgeColor: "bg-indigo-100 text-indigo-700 border-indigo-200",
    description: "Easily onboard hundreds of students in seconds using our standardized Excel spreadsheet template with instant pre-validation and error checks.",
    features: [
      "Standardized Excel / CSV spreadsheet template download",
      "Auto-assignment of class, section, roll number, and parent accounts",
      "Pre-upload validation with line-by-line error highlighting",
      "One-click creation of student and parent login credentials",
    ],
    webImage: "/Tour/Web_Bulk_Student_Upload.png",
    mobileImage: "/Tour/Mobile_Student_Lists.png",
    webUrl: "myschool.app/admin/students",
  },
  {
    id: "student-roster",
    category: "admin",
    categoryLabel: "Communication & Admin",
    title: "Student Directory & Roster",
    roleBadge: "Student Records",
    badgeColor: "bg-indigo-100 text-indigo-700 border-indigo-200",
    description: "Complete student record management with class/section filtering, profile photo uploads, parent linking, and credential management.",
    features: [
      "Class, section, and keyword search filters",
      "Individual student profiles with roll numbers and contact info",
      "Profile avatar management stored in database",
      "Account status, credential sharing, and parent relationship management",
    ],
    webImage: "/Tour/Web_Student_Lists.png",
    mobileImage: "/Tour/Mobile_Student_Lists.png",
    webUrl: "myschool.app/admin/students",
  },
  {
    id: "teacher-directory",
    category: "admin",
    categoryLabel: "Communication & Admin",
    title: "Faculty Roster & Class Mapping",
    roleBadge: "Staff Management",
    badgeColor: "bg-violet-100 text-violet-700 border-violet-200",
    description: "Faculty directory for organizing teaching staff, designating class teachers, assigning subjects, and managing contact credentials.",
    features: [
      "Teacher roster with department and qualification details",
      "Class teacher and subject teacher assignment workflows",
      "Profile photo management and contact information",
      "Status tracking and credential management",
    ],
    webImage: "/Tour/Web_Teacher_Lists.png",
    mobileImage: "/Tour/Mobile_Teacher_Lists.png",
    webUrl: "myschool.app/admin/teachers",
  },
];
