// packages/shared/constants/plans.ts
import { Plan } from "../types";

export const PLANS: Plan[] = [
  {
    id: "BASIC",
    name: "Basic",
    monthlyPrice: 1999,
    yearlyPrice: 19990,
    maxAdmins: 1,
    maxPrincipals: 1,
    maxTeachers: 30,
    maxStudents: 500,
    maxParents: 500,
    features: [
      "1 Admin + 1 Principal",
      "Up to 30 Teachers",
      "Up to 500 Students",
      "Attendance & Marks",
      "Homework & Announcements",
      "Parent App Access",
      "Basic Analytics",
    ],
  },
  {
    id: "STANDARD",
    name: "Standard",
    monthlyPrice: 3999,
    yearlyPrice: 39990,
    maxAdmins: 1,
    maxPrincipals: 1,
    maxTeachers: 50,
    maxStudents: 1000,
    maxParents: 1000,
    features: [
      "Everything in Basic",
      "Up to 50 Teachers",
      "Up to 1000 Students",
      "Advanced Analytics & Charts",
      "Exam Rank Reports",
      "Priority Support",
      "Custom Theme Color",
    ],
    popular: true,
  },
  {
    id: "PREMIUM",
    name: "Premium",
    monthlyPrice: 6999,
    yearlyPrice: 69990,
    maxAdmins: 1,
    maxPrincipals: 1,
    maxTeachers: 100,
    maxStudents: 2000,
    maxParents: 2000,
    features: [
      "Everything in Standard",
      "Up to 100 Teachers",
      "Up to 2000 Students",
      "Multi-branch Ready",
      "Advanced Reports (PDF)",
      "Dedicated Support",
      "API Access",
    ],
  },
];
